WITH BOOK_AUTHOR AS (
SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, A.AUTHOR_NAME
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID)

# SELECT * FROM BOOK_AUTHOR;

SELECT BA.AUTHOR_ID, BA.AUTHOR_NAME, BA.CATEGORY, SUM(S.SALES * BA.PRICE) AS TOTAL_SALES
FROM BOOK_AUTHOR BA
JOIN BOOK_SALES S ON BA.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY BA.AUTHOR_ID, BA.CATEGORY
ORDER BY BA.AUTHOR_ID , BA.CATEGORY DESC;
