-- 코드를 작성해주세요
# WITH RECURSIVE GEN AS (
# SELECT ID, PARENT_ID, 1 AS GENERATION
# FROM ECOLI_DATA
# WHERE PARENT_ID IS NULL

# UNION ALL

# SELECT E.id, E.parent_id, G.generation + 1
# FROM ECOLI_DATA E JOIN GEN G ON E.parent_id = G.id)

WITH RECURSIVE GEN AS (
SELECT ID, PARENT_ID, 1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL

SELECT E.id, E.parent_id, G.generation + 1
FROM ECOLI_DATA E JOIN GEN G ON E.parent_id = G.id)

SELECT ID FROM GEN WHERE GENERATION = 3;