# -- 코드를 입력하세요
# WITH TOTAL_SALES AS (
# SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE LIKE '2022-03%'

# UNION ALL

# SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE LIKE '2022-03%')

# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM TOTAL_SALES
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

#-----------------------------------------------------------------------------------

WITH TOTAL_SALES AS (
SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM TOTAL_SALES
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
