-- 코드를 작성해주세요
# SELECT e.ID AS ID, 
#     CASE 
#         WHEN e.PERCENT <= 0.25 THEN 'CRITICAL'
#         WHEN e.PERCENT <= 0.5 THEN 'HIGH'
#         WHEN e.PERCENT <= 0.75 THEN 'MEDIUM'
#         ELSE 'LOW'
#     END AS COLONY_NAME
# FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
#      FROM ECOLI_DATA) e
# ORDER BY ID;

# SELECT ID, CASE
#     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
#     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
#     WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
#     ELSE 'LOW'
#     END AS COLONY_NAME
# FROM ECOLI_DATA
# ORDER BY ID;

# SELECT e.ID AS ID, 
#     CASE 
#         WHEN e.PERCENT <= 0.25 THEN 'CRITICAL'
#         WHEN e.PERCENT <= 0.5  THEN 'HIGH'
#         WHEN e.PERCENT <= 0.75 THEN 'MEDIUM'
#         ELSE 'LOW'
#     END AS COLONY_NAME
# FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
#      FROM ECOLI_DATA) e
# ORDER BY ID;

SELECT e.ID AS ID, CASE
    WHEN e.RANKING = 1 THEN 'CRITICAL'
    WHEN e.RANKING = 2 THEN 'HIGH'
    WHEN e.RANKING = 3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
     FROM ECOLI_DATA) e
ORDER BY ID;