-- 코드를 입력하세요
WITH AVG_DIFF AS (
SELECT DISTINCT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVG_RENT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
)

# SELECT * FROM AVG_DIFF;

SELECT C.CAR_ID, AVG_RENT AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN AVG_DIFF A ON C.CAR_ID = A.CAR_ID
WHERE AVG_RENT >= 7
GROUP BY C.CAR_ID
ORDER BY AVG_RENT DESC, CAR_ID DESC;
