-- 코드를 작성해주세요
WITH QUARTER_TBL AS (
SELECT ID, PARENT_ID, 
(CASE
    WHEN MONTH(DIFFERENTIATION_DATE) IN (1, 2, 3) THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) IN (4, 5, 6) THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) IN (7, 8, 9) THEN '3Q'
    ELSE '4Q'
END) AS DEV_QUARTER
FROM ECOLI_DATA)

SELECT DEV_QUARTER AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM QUARTER_TBL
GROUP BY QUARTER;
