-- 코드를 입력하세요
WITH SALES AS (
SELECT SUM(H.TOTAL_ORDER + J.TOTAL_ORDER) AS ORDERS, H.FLAVOR
FROM FIRST_HALF H
JOIN JULY J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY ORDERS DESC
LIMIT 3)

SELECT FLAVOR
FROM SALES;