-- 코드를 입력하세요
WITH PT_APNT AS (
SELECT A.APNT_YMD, A.APNT_NO, A.PT_NO, A.MCDP_CD, A.MDDR_ID, A.APNT_CNCL_YN, A.APNT_CNCL_YMD, P.PT_NAME
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS' AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13')

# SELECT * FROM PT_APNT;

SELECT PA.APNT_NO, PA.PT_NAME, PA.PT_NO, PA.MCDP_CD, D.DR_NAME, PA.APNT_YMD
FROM PT_APNT PA
JOIN DOCTOR D ON PA.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD;