-- 코드를 입력하세요
# WITH RECURSIVE RC AS (
#     SELECT 0 AS H
#     UNION ALL 
#     SELECT H + 1 FROM RC WHERE H < 23)
    
# SELECT RC.H, COUNT(HOUR(DATETIME)) AS COUNT
# FROM RC
# LEFT JOIN ANIMAL_OUTS O ON RC.H = HOUR(O.DATETIME)
# GROUP BY RC.H
# ORDER BY RC.H;

WITH RECURSIVE RC AS(
SELECT 0 AS H
UNION ALL
SELECT H + 1
FROM RC WHERE H < 23)


SELECT H AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
# SELECT RC.H, COUNT(HOUR(DATETIME)) AS COUNT
FROM RC
LEFT JOIN ANIMAL_OUTS O ON HOUR(O.DATETIME) = H
GROUP BY H
ORDER BY H;



