-- 코드를 입력하세요
SELECT M.MEMBER_NAME as MEMBER_NAME, R.review_text as REVIEW_TEXT, DATE_FORMAT(R.review_date, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.member_id = R.member_id
WHERE M.member_id = (SELECT MEMBER_ID FROM REST_REVIEW R2 GROUP BY R2.member_id ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY 3 ASC, 2 ASC;

