-- 코드를 작성해주세요
WITH FISHES AS (
SELECT I.ID, I.FISH_TYPE, I.LENGTH, N.FISH_NAME
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE)

# SELECT * FROM FISHES;

SELECT ID, FISH_NAME, LENGTH
FROM FISHES
WHERE (FISH_TYPE, LENGTH) IN (
SELECT I2.FISH_TYPE, MAX(I2.LENGTH)
FROM FISH_INFO I2
GROUP BY I2.FISH_TYPE)
ORDER BY ID;